In [1]:
import arviz as az
import h5netcdf
import numpy as np
import seaborn as sns

from flipv3.flip_dsets import load_nuclease_data, load_pdz_dataset
from scistanpy import Model, parameters, results

In [7]:
res = results.SampleResults.from_disk(
    "/home/bwittmann/GitRepos/SciStanPy/amlt/small-8/small-8_53/trpb/libI/trpb_libI_lomax_sigmoid_diagnosed.nc",
    skip_fit=True,
)

In [8]:
_ = res.identify_failed_diagnostics()

Sample diagnostic tests results' summaries:
-------------------------------------------
0 of 16000 (0.00%) samples had a low energy.
8000 of 16000 (50.00%) samples reached the maximum tree depth.
0 of 16000 (0.00%) samples diverged.

R_hat diagnostic tests results' summaries:
------------------------------------------
9096 of 9121 (99.73%) r_hats tests failed for log_theta_t0.
7920 of 9121 (86.83%) r_hats tests failed for log_r_mean.
16497 of 18242 (90.43%) r_hats tests failed for r.
1 of 1 (100.00%) r_hats tests failed for c.
72429 of 72968 (99.26%) r_hats tests failed for raw_abundances_tg0.
72027 of 72968 (98.71%) r_hats tests failed for log_theta_tg0.

Ess_bulk diagnostic tests results' summaries:
---------------------------------------------
8999 of 9121 (98.66%) ess_bulks tests failed for log_theta_t0.
7100 of 9121 (77.84%) ess_bulks tests failed for log_r_mean.
14650 of 18242 (80.31%) ess_bulks tests failed for r.
1 of 1 (100.00%) ess_bulks tests failed for c.
71080 of 72968 (97

In [3]:
res.plot_variable_failure_quantile_traces()

BokehModel(combine_events=True, render_bundle={'docs_json': {'afc74a7e-2cb6-48b2-aa01-b675254d0f78': {'version…

In [11]:
res.inference_obj.variable_diagnostic_stats.codon_noise.sel(metric="r_hat").values

array(1.01092112)

In [15]:
tests = (
    res.inference_obj.variable_diagnostic_stats.experimental_mean_log_fluorescence.sel(
        metric="r_hat"
    ).values
)
fails = np.nonzero(tests > 1.01)

In [10]:
tests[fails]

array([1.0101633 , 1.01090526, 1.0100447 , 1.0100919 , 1.01093604,
       1.01240007, 1.0108254 , 1.01010583, 1.0133017 , 1.01173821,
       1.01020458, 1.01032946, 1.01148112, 1.01187091, 1.01259246,
       1.01232946, 1.0114285 , 1.01187868, 1.01088242, 1.01328922,
       1.0112063 , 1.01038144, 1.01089741, 1.01226734, 1.01035921,
       1.01101608, 1.01137904, 1.01126627, 1.0102167 , 1.01035492,
       1.01563234, 1.01017983, 1.01021301, 1.01118728, 1.01007568,
       1.01080461, 1.01051856, 1.01254809, 1.0106605 , 1.0100465 ,
       1.01072855, 1.01003211, 1.01030293, 1.01102769, 1.01055401,
       1.01208943, 1.01019406])

In [ ]:
failvals = res.inference_obj.posterior.absolute_mean_log_fluorescence.values[..., fails]
failvals.min()

np.float32(0.134486)

In [19]:
res.inference_obj.posterior.experimental_mean_log_fluorescence.values.mean()

np.float32(-3.2634172)

In [7]:
res.inference_obj.posterior.experimental_noise.values.std()

np.float32(0.0028209663)

In [8]:
res.inference_obj.posterior.experimental_noise.values.mean()

np.float32(0.38179016)

In [8]:
fails

(array([    0,   181,   542,   582,  1109,  6101,  8121,  8672, 17637]),)

In [13]:
res.inference_obj.observed_data.oc1[:, fails[0]]

<xarray.DataArray 'oc1' (a: 4, b: 9)> Size: 144B
array([[ 18384,   6676,      3,   2776,     27,   3171,     14,      2,
             5],
       [   393,  10372,      0,   2186,      2,     15,      0,      0,
             1],
       [   277,  53748,      5,   2828,      2,     19,      9,     12,
            11],
       [    86, 163988,     10,   3019,      3,   1116,      0,      0,
             0]], dtype=int32)
Dimensions without coordinates: a, b

In [14]:
for var in ("ic1", "oc1"):
    print(var)
    print(getattr(res.inference_obj.observed_data, var).values[..., fails[0]])

ic1
[50702 19752   841  6500   423  1875   480   538   586]
oc1
[[ 18384   6676      3   2776     27   3171     14      2      5]
 [   393  10372      0   2186      2     15      0      0      1]
 [   277  53748      5   2828      2     19      9     12     11]
 [    86 163988     10   3019      3   1116      0      0      0]]


In [10]:
res.inference_obj.observed_data.timepoint_counts.values[:, fails]

AttributeError: 'Dataset' object has no attribute 'timepoint_counts'

In [ ]:
totals = (
    res.inference_obj.observed_data.starting_counts.values
    + res.inference_obj.observed_data.timepoint_counts.values
)

In [ ]:
totals[:, fails]

array([[[ 4, 24,  0]],

       [[13,  0, 48]],

       [[ 7,  0,  0]]], dtype=int32)

In [ ]:
(
    np.sum(
        (
            res.inference_obj.observed_data.timepoint_counts.values[
                :,
                np.nonzero(
                    res.inference_obj.observed_data.timepoint_counts.values == 0
                )[1],
            ]
        )
        == 0,
        axis=0,
    )
    > 1
).sum()

np.int64(2257)