In [1]:
# import dms_stan.operations as dms_ops

from flipv3.flip_dsets import load_nuclease_data
from flipv3.nuclease_models import G1Lomax
from scistanpy.model.components import parameters
# from dms_stan import Model

# import pandas as pd

# from flipv3.trpb_models import get_trpb_instance
# from flipv3.pdz3_models import get_pdz3_instance
# from flipv3.flip_dsets import load_trpb_dataset, load_pdz_dataset
# from dms_stan import utils
# from dms_stan.model.components.abstract_model_component import AbstractModelComponent

In [2]:
data = load_nuclease_data(
    processed_data_dir="/home/bwittmann/GitRepos/SciStanPy/flip3_data/raw_data/nuclease/processed_data",
    processed_fiducial_data_dir="/home/bwittmann/GitRepos/SciStanPy/flip3_data/raw_data/nuclease/processed_fiducial_data",
    gen="G1"
)
_ = data.pop("variants")

In [3]:
model = G1Lomax(**data)

In [6]:
test = model.to_stan(output_dir="tmp", force_compile=True)

17:00:29 - cmdstanpy - INFO - compiling stan file /home/bwittmann/GitRepos/SciStanPy/tmp/model.stan to exe file /home/bwittmann/GitRepos/SciStanPy/tmp/model
17:00:53 - cmdstanpy - INFO - compiled model executable: /home/bwittmann/GitRepos/SciStanPy/tmp/model
17:00:53 - cmdstanpy - WARNING - Stan compiler has produced 6 warnings:
17:00:53 - cmdstanpy - WARNING - 
--- Translating Stan model to C++ code ---
bin/stanc --filename-in-msg=model.stan --warn-pedantic --O1 --include-paths=/home/bwittmann/GitRepos/SciStanPy/scistanpy/model/stan,/home/bwittmann/GitRepos/SciStanPy/scistanpy/model/stan --o=/home/bwittmann/GitRepos/SciStanPy/tmp/model.hpp /home/bwittmann/GitRepos/SciStanPy/tmp/model.stan
    no prior is provided, or the prior(s) depend on data variables. In the
    later case, this may be a false positive.
    is provided, or the prior(s) depend on data variables. In the later case,
    this may be a false positive.
    prior is provided, or the prior(s) depend on data variables. In 

In [5]:
for gc in ("exponential", "sigmoid"):
    for gr in ("exponential", "lomax", "gamma"):
        for lib in ("cis", "cript-c", "cript-n", "trans-1", "trans-2"):
            model = get_pdz3_instance(
                filepath = f"/home/bwittmann/GitRepos/SciStanPy/flip3_data/counts/pdz/{lib}.tsv",
                growth_curve=gc,
                growth_rate=gr
            )
            test = model.to_stan(output_dir="tmp", force_compile=True)

NameError: name 'get_pdz3_instance' is not defined

In [ ]:
gc

'exponential'

In [ ]:
data = load_trpb_dataset("/home/bwittmann/GitRepos/SciStanPy/flip3_data/counts/trpb/libA.csv")

In [ ]:
data["timepoint_counts"].shape

(2, 1, 9254)

In [ ]:
# nuclease_data = load_nuclease_data(
#     "/home/bwittmann/GitRepos/DMSStan/flip3_data/raw_data/nuclease/processed_data",
#     "/home/bwittmann/GitRepos/DMSStan/flip3_data/raw_data/nuclease/processed_fiducial_data",
#     "G1"
# )

NameError: name 'load_nuclease_data' is not defined

In [ ]:
nuclease_data.keys()

dict_keys(['dataset', 'data_indices', 'fiducial_indices', 'variants', 'ic1', 'ic2', 'ic3', 'lc', 'hc1', 'hc2', 'hc3'])

In [ ]:
data, fiducial = nuclease_data["data"], nuclease_data["fiducial"]

# Drop fiducial sequences from the data
fiducial_muts = fiducial.mutations.unique()
data = data[~data.mutations.isin(fiducial_muts)]

# Combine fiducial and data
combined = pd.concat([data, fiducial], ignore_index=True)

# Get indices for fiducial and non-fiducial sequences
data_indices = combined[~combined.mutations.isin(fiducial_muts)].index.to_numpy()
fiducial_indices = {mut: combined[combined.mutations == mut].index.to_numpy() for mut in fiducial_muts}

In [ ]:
len(fiducial_indices[""])

310

In [ ]:
len(fiducial)

310

In [ ]:
combined

mutations  read_count_1_high_g1  read_count_1_input_g1  \
0          H62W                   3.0                   87.0   
1          H62Y                  21.0                   17.0   
2          I54A                   0.0                   10.0   
3          I54C                   4.0                   43.0   
4          I54D                   2.0                   32.0   
...         ...                   ...                    ...   
11064                             0.0                    0.0   
11065                             4.0                   10.0   
11066                            98.0                   13.0   
11067                           123.0                   42.0   
11068                            97.0                    7.0   

       read_count_1_low_g1  read_count_2_high_g1  read_count_2_input_g1  \
0                    195.0                   0.0                   51.0   
1                     50.0                   6.0                   20.0   
2                      1.0                   0.0                   13.0   
3                      5.0                   0.0                   73.0   
4                      1.0                   0.0                   45.0   
...                    ...                   ...                    ...   
11064                  1.0                   0.0                    0.0   
11065                 17.0                   5.0                    2.0   
11066                 39.0                  21.0                    9.0   
11067                 77.0                  11.0                   17.0   
11068                 19.0                   8.0                    5.0   

       read_count_2_low_g1  read_count_3_high_g1  read_count_3_input_g1  \
0                    209.0                   4.0                   88.0   
1                     62.0                  92.0                   23.0   
2                      5.0                   0.0                   18.0   
3                     13.0                   0.0                   58.0   
4                     12.0                   1.0                   57.0   
...                    ...                   ...                    ...   
11064                  0.0                   1.0                    4.0   
11065                 24.0                  54.0                    7.0   
11066                 33.0                 251.0                   22.0   
11067                147.0                 506.0                   37.0   
11068                 26.0                 174.0                   11.0   

       read_count_3_low_g1  ...  ef_1_low_g1  ef_2_low_g1  ef_3_low_g1  \
0                    321.0  ...     2.789814     3.085470     2.533796   
1                     97.0  ...     2.312217     2.958588     2.474891   
2                      7.0  ...     0.057674     0.297567     0.222743   
3                      8.0  ...     0.085443     0.229237     0.075426   
4                     12.0  ...     0.026365     0.326473     0.174558   
...                    ...  ...          ...          ...          ...   
11064                  3.0  ...     0.191521     0.000000     0.317004   
11065                 38.0  ...     3.557953     5.183187     4.387941   
11066                 57.0  ...     3.369146     2.941734     2.716789   
11067                237.0  ...     2.640536     5.201792     4.484103   
11068                 38.0  ...     3.135967     4.428183     3.460409   

       pvalue_gen_g1_ref_neg_control_2_high_reseq_right  \
0                                               0.57156   
1                                               0.06447   
2                                               0.57156   
3                                               0.57156   
4                                               0.57156   
...                                                 ...   
11064                                               NaN   
11065                                               NaN   
11066          

In [ ]:
fiducial_muts

array([''], dtype=object)

In [ ]:
nuclease_data["data"]

mutations  \
0                                                          
1                                                   H62W   
2                                                   H62Y   
3                                                   I54A   
4                                                   I54C   
...                                                  ...   
10755  Y25I_S26L_P27L_Q28S_H29M_A30P_E31K_G32A_A33L_A...   
10756  Y25F_S26L_P27L_Q28S_H29M_A30P_E31K_G32A_A33L_A...   
10757  Y25I_S26L_P27L_Q28S_H29M_A30P_E31K_G32A_A33L_A...   
10758  Y25I_S26L_P27L_Q28S_H29M_A30P_E31K_G32A_A33L_A...   
10759  Y25F_P27S_Q28A_H29C_A30R_E31R_G32R_A33C_A34K_R...   

       read_count_1_high_g1  read_count_1_input_g1  read_count_1_low_g1  \
0                  104673.0                19361.0              60510.0   
1                       3.0                   87.0                195.0   
2                      21.0                   17.0                 50.0   
3                       0.0                   10.0                  1.0   
4                       4.0                   43.0                  5.0   
...                     ...                    ...                  ...   
10755                   0.0                    0.0                  0.0   
10756                  20.0                    3.0                 13.0   
10757                 108.0                   28.0                 93.0   
10758                   0.0                    7.0                  1.0   
10759                  18.0                    1.0                 12.0   

       read_count_2_high_g1  read_count_2_input_g1  read_count_2_low_g1  \
0                   47566.0                14033.0              53702.0   
1                       0.0                   51.0                209.0   
2                       6.0                   20.0                 62.0   
3                       0.0                   13.0                  5.0   
4                       0.0                   73.0                 13.0   
...                     ...                    ...                  ...   
10755                   0.0                    0.0                  0.0   
10756                  10.0                    5.0                 12.0   
10757                  37.0                   11.0                 35.0   
10758                   0.0                    1.0                  0.0   
10759                   9.0                    0.0                  6.0   

       read_count_3_high_g1  read_count_3_input_g1  read_count_3_low_g1  ...  \
0                  348205.0                23619.0             109363.0  ...   
1                       4.0                   88.0                321.0  ...   
2                      92.0                   23.0                 97.0  ...   
3                       0.0                   18.0                  7.0  ...   
4                       0.0                   58.0                  8.0  ...   
...                     ...                    ...                  ...  ...   
10755                   0.0                    0.0                  0.0  ...   
10756                  53.0                    6.0                 18.0  ...   
10757                  58.0                    7.0                176.0  ...   
10758                   0.0                    0.0                  3.0  ...   
10759                   5.0                    2.0                 19.0  ...   

       ef_2_high_reseq_g1  ef_1_low_g1  ef_2_low_g1  ef_3_low_g1  \
0                3.165749     2.826302     2.588309     2.818303   
1                0.000000     2.789814     3.085470     2.533796   
2                0.444519     2.312217     2.958588     2.474891   
3                0.000000     0.057674     0.297567     0.222743   
4                0.000000     0.085443     0.229237     0.075426   
...                   ...          ...          ...          ...   
10755            0.000000     0.000000     0.000000     0.000000   
10756            2.

In [ ]:
nuclease_data["fiducial"]

nuc_mutations mutations  \
0                                                   ()             
1                                   (('C', 228, 'T'),)             
2                                   (('C', 228, 'G'),)             
3                                   (('C', 228, 'A'),)             
4                                   (('C', 279, 'T'),)             
..                                                 ...       ...   
305  (('A', 312, 'G'), ('C', 327, 'T'), ('A', 428, ...             
306  (('C', 150, 'T'), ('G', 171, 'A'), ('A', 408, ...             
307  (('G', 129, 'T'), ('C', 366, 'A'), ('T', 396, ...             
308  (('T', 156, 'G'), ('G', 213, 'A'), ('C', 336, ...             
309  (('C', 150, 'A'), ('C', 228, 'T'), ('G', 255, ...             

     read_count_1_high_g1  read_count_1_input_g1  read_count_1_low_g1  \
0                 67886.0                12631.0              40972.0   
1                    18.0                    2.0                 15.0   
2                     4.0                    2.0                  0.0   
3                   256.0                   31.0                 93.0   
4                    70.0                   13.0                 57.0   
..                    ...                    ...                  ...   
305                   0.0                    0.0                  1.0   
306                   4.0                   10.0                 17.0   
307                  98.0                   13.0                 39.0   
308                 123.0                   42.0                 77.0   
309                  97.0                    7.0                 19.0   

     read_count_2_high_g1  read_count_2_input_g1  read_count_2_low_g1  \
0                 32105.0                 8996.0              35743.0   
1                    14.0                    1.0                 11.0   
2                     1.0                    0.0                  2.0   
3                   103.0                   14.0                 64.0   
4                    33.0                   12.0                 42.0   
..                    ...                    ...                  ...   
305                   0.0                    0.0                  0.0   
306                   5.0                    2.0                 24.0   
307                  21.0                    9.0                 33.0   
308                  11.0                   17.0                147.0   
309                   8.0                    5.0                 26.0   

     read_count_3_high_g1  read_count_3_input_g1  ...  \
0                233249.0                15168.0  ...   
1                    77.0                    6.0  ...   
2                     8.0                    1.0  ...   
3                   613.0                   32.0  ...   
4                   268.0                   19.0  ...   
..                    ...                    ...  ...   
305                   1.0                    4.0  ...   
306                  54.0                    7.0  ...   
307                 251.0                   22.0  ...   
308                 506.0                   37.0  ...   
309                 174.0                   11.0  ...   

     read_count_1_input_reseq_g1  read_count_2_high_reseq_g1  \
0                       146121.0                    298910.0   
1                           58.0                        86.0   
2                           20.0                        37.0   
3                          322.0                      1049.0   
4                          179.0                       319.0   
..                           ...                         ...   
305                         84.0                         9.0   
306                         40.0                        24.0   
307                        100.0                       129.0   
308                        314.0                       138.0   
309                         52.0                        61.0   

     read_count_

In [ ]:
ic = nuclease_data["g1"]["data"]["ic3"]
hc = nuclease_data["g1"]["data"]["hc3"]
(hc / hc.sum())  / (ic / ic.sum())

/tmp/ipykernel_2309660/102873779.py:3: RuntimeWarning: divide by zero encountered in divide
  (hc / hc.sum())  / (ic / ic.sum())
/tmp/ipykernel_2309660/102873779.py:3: RuntimeWarning: invalid value encountered in divide
  (hc / hc.sum())  / (ic / ic.sum())


array([[5.90812465],
       [0.01821602],
       [1.60300968],
       ...,
       [3.32052004],
       [       nan],
       [1.00188105]], shape=(10760, 1))

In [ ]:
hc

array([[348205],
       [     4],
       [    92],
       ...,
       [    58],
       [     0],
       [     5]], shape=(10760, 1))

In [ ]:
hc

array([[348205],
       [     4],
       [    92],
       ...,
       [    58],
       [     0],
       [     5]], shape=(10760, 1))

In [ ]:
(hc / hc.sum()) / (ic / ic.sum())

/tmp/ipykernel_2309660/2339704715.py:1: RuntimeWarning: divide by zero encountered in divide
  (hc / hc.sum()) / (ic / ic.sum())
/tmp/ipykernel_2309660/2339704715.py:1: RuntimeWarning: invalid value encountered in divide
  (hc / hc.sum()) / (ic / ic.sum())


array([3.60134115, 0.0332603 , 0.79053689, ..., 2.84852238, 0.        ,
       4.38449033], shape=(10760,))

array([8.04833583e-02, 2.39977486e-04, 7.38112570e-05, ...,
       1.03990244e-04, 1.81801126e-05, 1.19988743e-05], shape=(10760,))

In [ ]:
ic.sum()

np.int64(3045770)

In [ ]:
(
    (
        nuclease_data["g1"]["data"]["hc1"]
        * nuclease_data["g1"]["data"]["ic1"].sum(axis=0, keepdims=True)
    )
    / (nuclease_data["g1"]["data"]["ic1"] * nuclease_data["g1"]["data"]["hc1"].sum())
).mean(axis=1)

/tmp/ipykernel_2309660/4145450772.py:1: RuntimeWarning: divide by zero encountered in divide
  ((
/tmp/ipykernel_2309660/4145450772.py:1: RuntimeWarning: invalid value encountered in divide
  ((


array([3.94028528, 0.03085011, 0.88310731, ..., 2.96165356, 0.        ,
       9.27132569], shape=(10760,))

In [ ]:
(nuclease_data["g1"]["data"]["hc1"] / nuclease_data["g1"]["data"]["hc1"].sum())

array([[2.84618480e-01],
       [8.15736093e-06],
       [5.71015265e-05],
       ...,
       [2.93664994e-04],
       [0.00000000e+00],
       [4.89441656e-05]], shape=(10760, 1))

In [ ]:
nuclease_data["g1"]["data"]["ic1"].sum(axis=1)    / nuclease_data["g1"]["data"]["ic1"].sum()

array([7.90312466e-02, 2.45258178e-04, 7.22313241e-05, ...,
       1.03093799e-04, 1.87144794e-05, 1.11630228e-05], shape=(10760,))

In [ ]:
nuclease_data["g1"]["data"]["hc1"].sum(axis=0, keepdims=True)

array([[367766]])

In [ ]:
class NucleaseModel(Model):
    """Defines the DMS Stan model for the Nuclease dataset."""

    def __init__(
        self,
        data: MultiNucDatasetType,
        fluorescence_beta: float = 1.0,
        codon_noise_sigma: float = 0.1,
        experimental_noise_sigma: float = 0.1,
        g1_alpha: float = 1.0,
        g2_alpha: float = 1.0,
        g3_alpha: float = 1.0,
        g4_alpha: float = 1.0,
    ):

        # Store the raw data
        self.data = data

        # We have one true fluorescence value per variant. We define it on the
        # log scale
        self.mean_log_fluorescence = dms_components.ExpExponential(
            beta=fluorescence_beta, shape=(len(data["variants"]),)
        )

        # Define the generative model for the generation-specific fluorescence values
        self.generation_info = self._init_gen_fluorescence(
            codon_noise_sigma=codon_noise_sigma,
            experimental_noise_sigma=experimental_noise_sigma,
        )

        # Define input proportions. The proportions are defined as the fraction of
        # the total input population represented by a specific variant. Because
        # we have many variants, we define the input proportions on the log scale
        self._init_input_proportions(
            g1_alpha=g1_alpha,
            g2_alpha=g2_alpha,
            g3_alpha=g3_alpha,
            g4_alpha=g4_alpha,
        )

        # Calculate the proportions of the input populations that we expect to make
        # it through a given filter. We assume that all variants experience the
        # same noise resulting from differing codon usage. Experimental noise is
        # already baked into the system.
        self._calculate_output_proportions()

    def _init_gen_fluorescence(
        self, codon_noise_sigma: float, experimental_noise_sigma: float
    ):
        """
        Initializes codon-level fluorescence values for the fiducial and nonfiducial
        variants.
        """
        # We expect at least two sources of noise. One comes from different expression
        # levels resulting from different codons and the other comes from slight
        # differences in conditions between generations (i.e., other experimental
        # noise).
        self.codon_noise = dms_components.HalfNormal(sigma=codon_noise_sigma)
        self.experimental_noise = dms_components.HalfNormal(
            sigma=experimental_noise_sigma
        )

        # Define the fluorescence values for all generations
        generation_info: dict[str, tuple(int, int, int)] = {}
        for key in ("g1", "g2", "g3", "g4"):

            # Get the variant indices for fiducial and non-fiducial datasets
            fiducial_variant_inds = self.data[key]["fiducial"]["variant_inds"]
            data_variant_inds = self.data[key]["data"]["variant_inds"]

            # Ignore any data variants that are also present in the fiducial dataset.
            # This is to avoid double counting the fluorescence values for these
            # variants.
            data_variant_inds = np.setdiff1d(data_variant_inds, fiducial_variant_inds)

            # Get the mean fluorescence values for the population of droplets corresponding
            # to a specific variant in this generation. This part captures the cumulative
            # noise, which we assume to be normally distributed. To make sure we
            # keep on the log scale, we use the ExpNormal distribution, which models
            # a random variable whose exponential is normally distributed.
            fiducial_mean_log_fluorescence = f"{key}_mean_fid_log_fluorescence"
            data_mean_log_fluorescence = f"{key}_mean_log_fluorescence"
            n_fiducial_variants = len(fiducial_variant_inds)
            n_data_variants = len(data_variant_inds)
            setattr(
                self,
                fiducial_mean_log_fluorescence,
                dms_components.ExpNormal(
                    mu=dms_ops.exp(self.mean_log_fluorescence[fiducial_variant_inds]),
                    sigma=self.experimental_noise,
                    shape=(n_fiducial_variants, 1),
                ),
            )
            setattr(
                self,
                data_mean_log_fluorescence,
                dms_components.ExpNormal(
                    mu=dms_ops.exp(self.mean_log_fluorescence[data_variant_inds]),
                    sigma=self.experimental_noise,
                    shape=(n_data_variants,),
                ),
            )

            # Fiducial datasets have fluorescence values at the codon level. We
            # need to expand their mean fluorescence values to the codon level.
            # We would expect the fluorescence values here to be normally distributed
            # on the log scale (i.e., we expect a fold change in fluorescence for
            # different codons)
            n_fiducial_codons = self.data[key]["fiducial"]["ic1"].shape[-1]
            setattr(
                self,
                f"{key}_fid_codon_log_fluorescence",
                dms_components.Normal(
                    mu=getattr(self, fiducial_mean_log_fluorescence),
                    sigma=self.codon_noise,
                    shape=(n_fiducial_variants, n_fiducial_codons),
                ),
            )

            # Record information on this generation, including the number of non-fiducial
            # variants, the number of fiducial codon variants, and the total number
            # of variants (non-fiducial + fiducial codons variants) for which we
            # have count data.
            generation_info[key] = (
                n_data_variants,
                n_fiducial_codons,
                n_fiducial_variants + n_fiducial_codons,
            )

        # Return the generation information
        return generation_info

    def _init_input_proportions(
        self, g1_alpha: float, g2_alpha: float, g3_alpha: float, g4_alpha: float
    ):
        """
        Initializes the input proportions for each generation. The input proportions
        are defined as the fraction of the total input population represented by
        a specific variant.
        """
        # TODO: Consider a hyperprior for alpha in the cases where we have multiple
        # samples from the same Dirichlet distribution.
        self.g1_input_log_prop = dms_components.ExpDirichlet(
            alpha=g1_alpha,
            shape=(
                3,  # TODO: We are sure that there are three different samples here?
                self.generation_info["g1"][-1],
            ),
        )
        self.g2_input_log_prop = dms_components.ExpDirichlet(
            alpha=g2_alpha,
            shape=(
                2,  # TODO: We are sure that there are two different samples here?
                self.generation_info["g2"][-1],
            ),
        )
        self.g3_input_log_prop = dms_components.ExpDirichlet(
            alpha=g3_alpha,
            shape=self.generation_info["g3"][-1],
        )
        self.g4_input_log_prop = dms_components.ExpDirichlet(
            alpha=g4_alpha,
            shape=self.generation_info["g4"][-1],
        )

    def _calculate_output_proportions(self):
        """
        Calculates the expected output proportions for a population of variants
        whose mean log fluorescence values are defined by `self.{generation}_mean_log_fluorescence`.
        We assume that all variants experience the same noise resulting from differing
        codon usage, so we apply the codon noise inferred from the fiducial sequences
        to the non-fiducial sequences. We assume that all other system noise is
        captured when we define the generational mean fluorescence values from
        the overall mean fluorescence values. In other words, the proportion of
        variants that make it through a given filter is the proportion of variants
        above a certain threshold defined by the distribution of fluorescence
        values (i.e., the complementary CDF of the fluorescence values).
        """

        def single_calculation(
            input_log_prop: dms_components.ExpDirichlet,
            mean_log_fluorescence: dms_components.ExpNormal,
            threshold: npt.NDArray[np.floating],
        ) -> dms_components.TransformedParameter:
            """
            Returns the proportion of variants that are above a given threshold.
            Because our mean fluorescence is defined on the log scale, we need to
            use the CDF of the log-normal distribution to calculate the proportion
            of variants whose fluorescence values are above a given threshold.
            """
            # Get the log complementary CDF of the fluorescence values
            # TODO: Overload this function. It should be callable as an instance
            # or a class method.
            log_ccdf = dms_components.LogNormal(
                mu=mean_log_fluorescence, sigma=self.codon_noise
            ).log_ccdf(threshold)

            # Now update the input log proportions to reflect the decrease.
            raw_output_log_prop = input_log_prop + log_ccdf

            # Finally, renormalize the output log proportions such that they sum
            # to 1.0 across all variants. This is our output proportion.
            return dms_ops.normalize_log(raw_output_log_prop)

        # Calculate the output proportions, making sure to use the correct combinations
        # of input log proportions and fluorescence thresholds for each generation.
        for key in ("g1", "g2", "g3", "g4"):

            # Calculate the output log proportions for this generation
            setattr(
                self,
                f"{key}_output_log_prop",
                single_calculation(
                    input_log_prop=getattr(self, f"{key}_input_log_prop"),
                    mean_log_fluorescence=getattr(self, f"{key}_mean_log_fluorescence"),
                    threshold=self.data[key]["ft"],
                ),
            )

    def _model_counts(self):
        """
        Defines the distributions that model our observations. These are all multinomial
        distributions parametrized by the log proportions of the variants.
        """

SyntaxError: expected ':' (1139892077.py, line 23)

In [ ]:
nuclease_data["g1"]["fiducial"]["variant_inds"]

array([0])